# SPARK network diagram https://www.icbm.com/docs/en/zpfas/1.1.0?topic=spark-configuring-networking-apache

version: '3.9'
services:
  spark-master:
    image: spark-base:v1
    build: .
    hostname: sparkmaster # This marks this container's local-ip as sparkmaster. Check /etc/hosts to confirm
    ports:
      - "7077:7077" # So we can call master from driver
      - "8080:8080" # Master web GUI
      - "9870:9870" # HDFS datanode web GUI for later
    env_file:
      - .env
    command: $SPARK_HOME/sbin/start-master.sh
    networks:
      - spark-network

  spark-worker-1:
    image: spark-base:v1
    command: $SPARK_HOME/sbin/start-worker.sh spark://sparkmaster:7077
    env_file:
      - .env
    networks:
      - spark-network

  spark-worker-2:
    image: spark-base:v1
    command: $SPARK_HOME/sbin/start-worker.sh spark://sparkmaster:7077
    env_file:
      - .env
    networks:
      - spark-network

networks:
  spark-network: {}
